ApiDebateList:
    pattern:  /debates
    defaults: { _controller: PolitizrFrontBundle:Api\ApiDebate:list }

ApiDebateShow:
    pattern:  /debates/{id}
    defaults: { _controller: PolitizrFrontBundle:Api\ApiDebate:show }
    requirements:
        _method:        GET
        id: "\d+"

ApiDebateCreate:
    pattern:  /debates/create
    defaults: { _controller: PolitizrFrontBundle:Api\ApiDebate:create }
    requirements:
        _method:        POST
